### ISSUE TITLE
Do not circumvent DVC filesystem

### ISSUE THREAD

**Issue by PythonFZ** [zincware/IPSuite#301]
First highlighted here, there should never be an exception to not go through the DVCFileSystem.

That is a good point. Actually I modified the ProcessAtoms base class which also uses that line, and have to admit that I don't know if it is needed. Maybe we can talk about the atoms and file handling so I can adjust this in the base class too?

_Originally posted by @Tetracarbonylnickel in https://github.com/zincware/IPSuite/pull/299#discussion_r1609383094_

**Comment by Tetracarbonylnickel** [comment]
resolved with PR #299
