### ISSUE TITLE
Node Groups

### ISSUE THREAD

**Issue by PythonFZ** [zincware/IPSuite#53]
We could provide Node Groups, that define multiple nodes together. E.g. metrics could be predict, metrics, force decomp all together.

Discussion: Furthermore, we don't really need PredictEithModel as it is basically Singlepoint where the calc is the model. Then we pass true/pred to the metrics node. This would probably make uncertainty easier as well, because we don't need the prediction class anymore. This would be easier with Node Groups.

**Comment by PythonFZ** [comment]
```python
def evaluate_model(model, true_data):
    predictions = ips.calculators.SinglePoint(model=model, data=true_data)
    metrics = ips.analysis.EvaluationMetrics(pred_data=predictions, true_data=true_data)
    force_comp = ips.analysis.ForceDecomposition(pred_data=predictions, true_data=true_data)

    return predictions, metrics, force_comp
```
or
```python
def evaluate_model(model, true_data):
    predictions = ips.calculators.SinglePoint(model=model, data=true_data)
    metrics = ips.analysis.EvaluationMetrics(data=predictions)
    force_comp = ips.analysis.ForceDecomposition(data=predictions)

    return predictions, metrics, force_comp

```

**Comment by PythonFZ** [comment]
> what is preventing users from doing this now?

Nothing, I was just wondering if we should supply such functions? Also if we should use the `predictions` dataclass or remove it in favour of Atoms objects with singlepoint calculators (I think we should)

**Comment by M-R-Schaefer** [comment]
> 
Perhaps it's possible to find nice collections of analysis nodes which are usually used together? E.g. for molecular liquids one could group box scale and force decomposition together. I can't think of many of such groupings from the top of my head   though

Regarding the prediction node: I am not particularly attached to it. Does keeping/removing it have an impact on how easy it is to store additional information for the structure, like uncertainty?

**Comment by PythonFZ** [comment]
> Regarding the prediction node: I am not particularly attached to it. Does keeping/removing it have an impact on how easy it is to store additional information for the structure, like uncertainty?

I do think it might actually be easier using atoms, because we can store it using ZnH5MD and the `calc.results` dict.
